# TCL File Generated by Component Editor 18.1
# Fri Sep 23 15:23:14 GMT-03:00 2022
# DO NOT MODIFY


# 
# data_recovery "data_recovery" v1.0
#  2022.09.23.15:23:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module data_recovery
# 
set_module_property DESCRIPTION ""
set_module_property NAME data_recovery
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME data_recovery
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL data_recovery
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file data_recovery.vhd VHDL PATH data_recovery.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL data_recovery
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file data_recovery.vhd VHDL PATH data_recovery.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL data_recovery
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file data_recovery.vhd VHDL PATH data_recovery.vhd


# 
# parameters
# 
add_parameter BYTES_COUNTER INTEGER 100
set_parameter_property BYTES_COUNTER DEFAULT_VALUE 100
set_parameter_property BYTES_COUNTER DISPLAY_NAME BYTES_COUNTER
set_parameter_property BYTES_COUNTER TYPE INTEGER
set_parameter_property BYTES_COUNTER UNITS None
set_parameter_property BYTES_COUNTER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BYTES_COUNTER HDL_PARAMETER true
add_parameter MIN_START_PULSE_CYCLES INTEGER 5
set_parameter_property MIN_START_PULSE_CYCLES DEFAULT_VALUE 5
set_parameter_property MIN_START_PULSE_CYCLES DISPLAY_NAME MIN_START_PULSE_CYCLES
set_parameter_property MIN_START_PULSE_CYCLES TYPE INTEGER
set_parameter_property MIN_START_PULSE_CYCLES UNITS None
set_parameter_property MIN_START_PULSE_CYCLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MIN_START_PULSE_CYCLES HDL_PARAMETER true
add_parameter TYPE_OF_RETURN INTEGER 0
set_parameter_property TYPE_OF_RETURN DEFAULT_VALUE 0
set_parameter_property TYPE_OF_RETURN DISPLAY_NAME TYPE_OF_RETURN
set_parameter_property TYPE_OF_RETURN TYPE INTEGER
set_parameter_property TYPE_OF_RETURN UNITS None
set_parameter_property TYPE_OF_RETURN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TYPE_OF_RETURN HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clk0
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clk0
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source data_valid_o valid Output 1
add_interface_port avalon_streaming_source parallel_data_o data Output 8


# 
# connection point clk0
# 
add_interface clk0 clock end
set_interface_property clk0 clockRate 0
set_interface_property clk0 ENABLED true
set_interface_property clk0 EXPORT_OF ""
set_interface_property clk0 PORT_NAME_MAP ""
set_interface_property clk0 CMSIS_SVD_VARIABLES ""
set_interface_property clk0 SVD_ADDRESS_GROUP ""

add_interface_port clk0 clk0 clk Input 1


# 
# connection point clk90
# 
add_interface clk90 clock end
set_interface_property clk90 clockRate 0
set_interface_property clk90 ENABLED true
set_interface_property clk90 EXPORT_OF ""
set_interface_property clk90 PORT_NAME_MAP ""
set_interface_property clk90 CMSIS_SVD_VARIABLES ""
set_interface_property clk90 SVD_ADDRESS_GROUP ""

add_interface_port clk90 clk90 clk Input 1


# 
# connection point lvds_i
# 
add_interface lvds_i conduit end
set_interface_property lvds_i associatedClock clk0
set_interface_property lvds_i associatedReset ""
set_interface_property lvds_i ENABLED true
set_interface_property lvds_i EXPORT_OF ""
set_interface_property lvds_i PORT_NAME_MAP ""
set_interface_property lvds_i CMSIS_SVD_VARIABLES ""
set_interface_property lvds_i SVD_ADDRESS_GROUP ""

add_interface_port lvds_i serial_data_i serial_data_i Input 1


# 
# connection point transition_found
# 
add_interface transition_found conduit end
set_interface_property transition_found associatedClock clk0
set_interface_property transition_found associatedReset reset_sink
set_interface_property transition_found ENABLED true
set_interface_property transition_found EXPORT_OF ""
set_interface_property transition_found PORT_NAME_MAP ""
set_interface_property transition_found CMSIS_SVD_VARIABLES ""
set_interface_property transition_found SVD_ADDRESS_GROUP ""

add_interface_port transition_found sop_o sop_o Output 1

