# This file was automatically generated by the swinfo2header utility.
# 
# Created from SOPC Builder system 'ccd_qsys' in
# file '../syn/altera/ccd_qsys.sopcinfo'.

# This file contains macros for module 'ejection_sim_0' and devices
# connected to the following master:
#   master_es
# 
# Do not include this header file and another header file created for a
# different module or master group at the same time.
# Doing so may result in duplicate macro names.
# Instead, use the system header file which has macros with unique names.


return 0
