# This file was automatically generated by the swinfo2header utility.
# 
# Created from SOPC Builder system 'ccd_qsys' in
# file '../syn/altera/ccd_qsys.sopcinfo'.

# This file contains macros for module 'fifo_to_ram_0' and devices
# connected to the following master:
#   avalon_master_0
# 
# Do not include this header file and another header file created for a
# different module or master group at the same time.
# Doing so may result in duplicate macro names.
# Instead, use the system header file which has macros with unique names.

# Macros for device 'sdram_tri_controller_0', class 'altera_sdram_tri_controller'
# The macros are prefixed with 'SDRAM_TRI_CONTROLLER_0_'.
# The prefix is the slave descriptor.
SDRAM_TRI_CONTROLLER_0_COMPONENT_TYPE=altera_sdram_tri_controller
SDRAM_TRI_CONTROLLER_0_COMPONENT_NAME=sdram_tri_controller_0
SDRAM_TRI_CONTROLLER_0_BASE=0x0
SDRAM_TRI_CONTROLLER_0_SPAN=33554432
SDRAM_TRI_CONTROLLER_0_END=0x1ffffff


return 0
