# TCL File Generated by Component Editor 18.1
# Tue Oct 24 14:34:23 GMT-03:00 2023
# DO NOT MODIFY


# 
# ad_split_data "ad_split_data" v1.0
#  2023.10.24.14:34:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ad_split_data
# 
set_module_property DESCRIPTION ""
set_module_property NAME ad_split_data
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ad_split_data
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ad_split
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ad-split-data.vhd VHDL PATH ad_split_data.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point ad
# 
add_interface ad avalon_streaming end
set_interface_property ad associatedClock clock_sink
set_interface_property ad associatedReset reset_sink
set_interface_property ad dataBitsPerSymbol 48
set_interface_property ad errorDescriptor ""
set_interface_property ad firstSymbolInHighOrderBits true
set_interface_property ad maxChannel 0
set_interface_property ad readyLatency 0
set_interface_property ad ENABLED true
set_interface_property ad EXPORT_OF ""
set_interface_property ad PORT_NAME_MAP ""
set_interface_property ad CMSIS_SVD_VARIABLES ""
set_interface_property ad SVD_ADDRESS_GROUP ""

add_interface_port ad asi_ad_data_i data Input 48
add_interface_port ad asi_ad_valid_i valid Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink sysclk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point ad_odd
# 
add_interface ad_odd avalon_streaming start
set_interface_property ad_odd associatedClock clock_sink
set_interface_property ad_odd associatedReset reset_sink
set_interface_property ad_odd dataBitsPerSymbol 32
set_interface_property ad_odd errorDescriptor ""
set_interface_property ad_odd firstSymbolInHighOrderBits true
set_interface_property ad_odd maxChannel 0
set_interface_property ad_odd readyLatency 0
set_interface_property ad_odd ENABLED true
set_interface_property ad_odd EXPORT_OF ""
set_interface_property ad_odd PORT_NAME_MAP ""
set_interface_property ad_odd CMSIS_SVD_VARIABLES ""
set_interface_property ad_odd SVD_ADDRESS_GROUP ""

add_interface_port ad_odd aso_ad_valid_odd_o valid Output 1
add_interface_port ad_odd aso_ad_data_odd_o data Output 32


# 
# connection point ad_even
# 
add_interface ad_even avalon_streaming start
set_interface_property ad_even associatedClock clock_sink
set_interface_property ad_even associatedReset reset_sink
set_interface_property ad_even dataBitsPerSymbol 32
set_interface_property ad_even errorDescriptor ""
set_interface_property ad_even firstSymbolInHighOrderBits true
set_interface_property ad_even maxChannel 0
set_interface_property ad_even readyLatency 0
set_interface_property ad_even ENABLED true
set_interface_property ad_even EXPORT_OF ""
set_interface_property ad_even PORT_NAME_MAP ""
set_interface_property ad_even CMSIS_SVD_VARIABLES ""
set_interface_property ad_even SVD_ADDRESS_GROUP ""

add_interface_port ad_even aso_ad_valid_even_o valid Output 1
add_interface_port ad_even aso_ad_data_even_o data Output 32

