# TCL File Generated by Component Editor 18.1
# Thu Nov 17 10:23:17 GMT-03:00 2022
# DO NOT MODIFY


# 
# ad_module "ad_module" v1.0
#  2022.11.17.10:23:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ad_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME ad_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ad_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ad_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ad_module.vhd VHDL PATH ad_module.vhd TOP_LEVEL_FILE
add_fileset_file fifo_serdes_b.vhd VHDL PATH fifo_serdes_b.vhd
add_fileset_file fifo_serdes_gb.vhd VHDL PATH fifo_serdes_gb.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock pll_30_3_co
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point ad_i
# 
add_interface ad_i conduit end
set_interface_property ad_i associatedClock pll_30_3_co
set_interface_property ad_i associatedReset reset
set_interface_property ad_i ENABLED true
set_interface_property ad_i EXPORT_OF ""
set_interface_property ad_i PORT_NAME_MAP ""
set_interface_property ad_i CMSIS_SVD_VARIABLES ""
set_interface_property ad_i SVD_ADDRESS_GROUP ""

add_interface_port ad_i ad_0_data_i red_e_co Input 12
add_interface_port ad_i ad_1_data_i red_o_co Input 12
add_interface_port ad_i ad_2_data_i green_e_co Input 12
add_interface_port ad_i ad_3_data_i green_o_co Input 12
add_interface_port ad_i ad_4_data_i blue_e_co Input 12
add_interface_port ad_i ad_5_data_i blue_o_co Input 12


# 
# connection point ad_o
# 
add_interface ad_o conduit end
set_interface_property ad_o associatedClock pll_30_3_co
set_interface_property ad_o associatedReset reset
set_interface_property ad_o ENABLED true
set_interface_property ad_o EXPORT_OF ""
set_interface_property ad_o PORT_NAME_MAP ""
set_interface_property ad_o CMSIS_SVD_VARIABLES ""
set_interface_property ad_o SVD_ADDRESS_GROUP ""

add_interface_port ad_o ad_cplob_o cplob_co Output 1
add_interface_port ad_o ad_dataclk_o dataclk_co Output 1
add_interface_port ad_o ad_pblk_o pblk_co Output 1
add_interface_port ad_o ad_shd_o shd_co Output 1
add_interface_port ad_o ad_shp_o shp_co Output 1


# 
# connection point ccd_o
# 
add_interface ccd_o conduit end
set_interface_property ccd_o associatedClock pll_30_3_co
set_interface_property ccd_o associatedReset reset
set_interface_property ccd_o ENABLED true
set_interface_property ccd_o EXPORT_OF ""
set_interface_property ccd_o PORT_NAME_MAP ""
set_interface_property ccd_o CMSIS_SVD_VARIABLES ""
set_interface_property ccd_o SVD_ADDRESS_GROUP ""

add_interface_port ccd_o ccd_theta_1a_o theta_1a_co Output 1
add_interface_port ccd_o ccd_theta_2a_o theta_2a_co Output 1
add_interface_port ccd_o ccd_theta_2b_o theta_2b_co Output 1
add_interface_port ccd_o ccd_rs_o rs_co Output 1
add_interface_port ccd_o ccd_sh_o sh_co Output 1
add_interface_port ccd_o ccd_cp_o cp_co Output 1


# 
# connection point sync_i
# 
add_interface sync_i conduit end
set_interface_property sync_i associatedClock pll_30_3_co
set_interface_property sync_i associatedReset reset
set_interface_property sync_i ENABLED true
set_interface_property sync_i EXPORT_OF ""
set_interface_property sync_i PORT_NAME_MAP ""
set_interface_property sync_i CMSIS_SVD_VARIABLES ""
set_interface_property sync_i SVD_ADDRESS_GROUP ""

add_interface_port sync_i sync_i co Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock pll_30_3_co
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_ad_write_i write Input 1
add_interface_port avs avs_ad_addr_i address Input 4
add_interface_port avs avs_ad_data_i writedata Input 16
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pll_30_1_co
# 
add_interface pll_30_1_co clock end
set_interface_property pll_30_1_co clockRate 0
set_interface_property pll_30_1_co ENABLED true
set_interface_property pll_30_1_co EXPORT_OF ""
set_interface_property pll_30_1_co PORT_NAME_MAP ""
set_interface_property pll_30_1_co CMSIS_SVD_VARIABLES ""
set_interface_property pll_30_1_co SVD_ADDRESS_GROUP ""

add_interface_port pll_30_1_co pll_30_1_input clk Input 1


# 
# connection point pll_30_2_co
# 
add_interface pll_30_2_co clock end
set_interface_property pll_30_2_co clockRate 0
set_interface_property pll_30_2_co ENABLED true
set_interface_property pll_30_2_co EXPORT_OF ""
set_interface_property pll_30_2_co PORT_NAME_MAP ""
set_interface_property pll_30_2_co CMSIS_SVD_VARIABLES ""
set_interface_property pll_30_2_co SVD_ADDRESS_GROUP ""

add_interface_port pll_30_2_co pll_30_2_input clk Input 1


# 
# connection point pll_30_3_co
# 
add_interface pll_30_3_co clock end
set_interface_property pll_30_3_co clockRate 0
set_interface_property pll_30_3_co ENABLED true
set_interface_property pll_30_3_co EXPORT_OF ""
set_interface_property pll_30_3_co PORT_NAME_MAP ""
set_interface_property pll_30_3_co CMSIS_SVD_VARIABLES ""
set_interface_property pll_30_3_co SVD_ADDRESS_GROUP ""

add_interface_port pll_30_3_co pll_30_3_input clk Input 1


# 
# connection point pll_30_4_co
# 
add_interface pll_30_4_co clock end
set_interface_property pll_30_4_co clockRate 0
set_interface_property pll_30_4_co ENABLED true
set_interface_property pll_30_4_co EXPORT_OF ""
set_interface_property pll_30_4_co PORT_NAME_MAP ""
set_interface_property pll_30_4_co CMSIS_SVD_VARIABLES ""
set_interface_property pll_30_4_co SVD_ADDRESS_GROUP ""

add_interface_port pll_30_4_co pll_30_4_input clk Input 1


# 
# connection point pll_30_5_co
# 
add_interface pll_30_5_co clock end
set_interface_property pll_30_5_co clockRate 0
set_interface_property pll_30_5_co ENABLED true
set_interface_property pll_30_5_co EXPORT_OF ""
set_interface_property pll_30_5_co PORT_NAME_MAP ""
set_interface_property pll_30_5_co CMSIS_SVD_VARIABLES ""
set_interface_property pll_30_5_co SVD_ADDRESS_GROUP ""

add_interface_port pll_30_5_co pll_30_5_input clk Input 1


# 
# connection point ad_to_fifo
# 
add_interface ad_to_fifo avalon_streaming start
set_interface_property ad_to_fifo associatedClock pll_30_3_co
set_interface_property ad_to_fifo associatedReset reset
set_interface_property ad_to_fifo dataBitsPerSymbol 48
set_interface_property ad_to_fifo errorDescriptor ""
set_interface_property ad_to_fifo firstSymbolInHighOrderBits true
set_interface_property ad_to_fifo maxChannel 0
set_interface_property ad_to_fifo readyLatency 0
set_interface_property ad_to_fifo ENABLED true
set_interface_property ad_to_fifo EXPORT_OF ""
set_interface_property ad_to_fifo PORT_NAME_MAP ""
set_interface_property ad_to_fifo CMSIS_SVD_VARIABLES ""
set_interface_property ad_to_fifo SVD_ADDRESS_GROUP ""

add_interface_port ad_to_fifo aso_ad_data_analysis0_o data Output 48
add_interface_port ad_to_fifo aso_ad_valid_analysis0_o valid Output 1


# 
# connection point ad_to_sdram
# 
add_interface ad_to_sdram avalon_streaming start
set_interface_property ad_to_sdram associatedClock pll_30_3_co
set_interface_property ad_to_sdram associatedReset reset
set_interface_property ad_to_sdram dataBitsPerSymbol 48
set_interface_property ad_to_sdram errorDescriptor ""
set_interface_property ad_to_sdram firstSymbolInHighOrderBits true
set_interface_property ad_to_sdram maxChannel 0
set_interface_property ad_to_sdram readyLatency 0
set_interface_property ad_to_sdram ENABLED true
set_interface_property ad_to_sdram EXPORT_OF ""
set_interface_property ad_to_sdram PORT_NAME_MAP ""
set_interface_property ad_to_sdram CMSIS_SVD_VARIABLES ""
set_interface_property ad_to_sdram SVD_ADDRESS_GROUP ""

add_interface_port ad_to_sdram aso_ad_data_window_o data Output 48
add_interface_port ad_to_sdram aso_ad_valid_window_o valid Output 1


# 
# connection point ad_packet
# 
add_interface ad_packet avalon_streaming start
set_interface_property ad_packet associatedClock pll_30_3_co
set_interface_property ad_packet associatedReset reset
set_interface_property ad_packet dataBitsPerSymbol 48
set_interface_property ad_packet errorDescriptor ""
set_interface_property ad_packet firstSymbolInHighOrderBits true
set_interface_property ad_packet maxChannel 0
set_interface_property ad_packet readyLatency 0
set_interface_property ad_packet ENABLED true
set_interface_property ad_packet EXPORT_OF ""
set_interface_property ad_packet PORT_NAME_MAP ""
set_interface_property ad_packet CMSIS_SVD_VARIABLES ""
set_interface_property ad_packet SVD_ADDRESS_GROUP ""

add_interface_port ad_packet aso_ad_data_fifo_o data Output 48
add_interface_port ad_packet aso_ad_valid_fifo_o valid Output 1


# 
# connection point packet_save
# 
add_interface packet_save conduit end
set_interface_property packet_save associatedClock pll_30_3_co
set_interface_property packet_save associatedReset reset
set_interface_property packet_save ENABLED true
set_interface_property packet_save EXPORT_OF ""
set_interface_property packet_save PORT_NAME_MAP ""
set_interface_property packet_save CMSIS_SVD_VARIABLES ""
set_interface_property packet_save SVD_ADDRESS_GROUP ""

add_interface_port packet_save save_to_fifo_i save_to_fifo_co Input 1


# 
# connection point ad_to_fifo_3
# 
add_interface ad_to_fifo_3 avalon_streaming start
set_interface_property ad_to_fifo_3 associatedClock pll_30_3_co
set_interface_property ad_to_fifo_3 associatedReset reset
set_interface_property ad_to_fifo_3 dataBitsPerSymbol 48
set_interface_property ad_to_fifo_3 errorDescriptor ""
set_interface_property ad_to_fifo_3 firstSymbolInHighOrderBits true
set_interface_property ad_to_fifo_3 maxChannel 0
set_interface_property ad_to_fifo_3 readyLatency 0
set_interface_property ad_to_fifo_3 ENABLED true
set_interface_property ad_to_fifo_3 EXPORT_OF ""
set_interface_property ad_to_fifo_3 PORT_NAME_MAP ""
set_interface_property ad_to_fifo_3 CMSIS_SVD_VARIABLES ""
set_interface_property ad_to_fifo_3 SVD_ADDRESS_GROUP ""

add_interface_port ad_to_fifo_3 aso_ad_data_analysis3_o data Output 48
add_interface_port ad_to_fifo_3 aso_ad_valid_analysis3_o valid Output 1


# 
# connection point ad_to_fifo_2
# 
add_interface ad_to_fifo_2 avalon_streaming start
set_interface_property ad_to_fifo_2 associatedClock pll_30_3_co
set_interface_property ad_to_fifo_2 associatedReset reset
set_interface_property ad_to_fifo_2 dataBitsPerSymbol 48
set_interface_property ad_to_fifo_2 errorDescriptor ""
set_interface_property ad_to_fifo_2 firstSymbolInHighOrderBits true
set_interface_property ad_to_fifo_2 maxChannel 0
set_interface_property ad_to_fifo_2 readyLatency 0
set_interface_property ad_to_fifo_2 ENABLED true
set_interface_property ad_to_fifo_2 EXPORT_OF ""
set_interface_property ad_to_fifo_2 PORT_NAME_MAP ""
set_interface_property ad_to_fifo_2 CMSIS_SVD_VARIABLES ""
set_interface_property ad_to_fifo_2 SVD_ADDRESS_GROUP ""

add_interface_port ad_to_fifo_2 aso_ad_valid_analysis2_o valid Output 1
add_interface_port ad_to_fifo_2 aso_ad_data_analysis2_o data Output 48


# 
# connection point ad_to_fifo_1
# 
add_interface ad_to_fifo_1 avalon_streaming start
set_interface_property ad_to_fifo_1 associatedClock pll_30_3_co
set_interface_property ad_to_fifo_1 associatedReset reset
set_interface_property ad_to_fifo_1 dataBitsPerSymbol 48
set_interface_property ad_to_fifo_1 errorDescriptor ""
set_interface_property ad_to_fifo_1 firstSymbolInHighOrderBits true
set_interface_property ad_to_fifo_1 maxChannel 0
set_interface_property ad_to_fifo_1 readyLatency 0
set_interface_property ad_to_fifo_1 ENABLED true
set_interface_property ad_to_fifo_1 EXPORT_OF ""
set_interface_property ad_to_fifo_1 PORT_NAME_MAP ""
set_interface_property ad_to_fifo_1 CMSIS_SVD_VARIABLES ""
set_interface_property ad_to_fifo_1 SVD_ADDRESS_GROUP ""

add_interface_port ad_to_fifo_1 aso_ad_data_analysis1_o data Output 48
add_interface_port ad_to_fifo_1 aso_ad_valid_analysis1_o valid Output 1

