# TCL File Generated by Component Editor 18.1
# Sat Oct 21 16:45:07 BRST 2023
# DO NOT MODIFY


# 
# rj45_tester "RJ45 Proprietary LVDS bus Tester" v1.0
#  2023.10.21.16:45:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rj45_tester
# 
set_module_property DESCRIPTION ""
set_module_property NAME rj45_tester
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "RJ45-Pair Proprietary LVDS bus Tester"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rjtester
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file rjtester.vhd VHDL PATH rjtester.vhd TOP_LEVEL_FILE
add_fileset_file framecmp.vhd VHDL PATH frame/framecmp.vhd
add_fileset_file framegen.vhd VHDL PATH frame/framegen.vhd
add_fileset_file des.vhd VHDL PATH serdes/des.vhd
add_fileset_file ser.vhd VHDL PATH serdes/ser.vhd
add_fileset_file data_recovery.vhd VHDL PATH serdes/fpga-lib-analog-data_recovery/data_recovery.vhd


# 
# parameters
# 
add_parameter PERIOD_SYNC_US INTEGER 100
set_parameter_property PERIOD_SYNC_US DEFAULT_VALUE 100
set_parameter_property PERIOD_SYNC_US DISPLAY_NAME PERIOD_SYNC_US
set_parameter_property PERIOD_SYNC_US TYPE INTEGER
set_parameter_property PERIOD_SYNC_US UNITS None
set_parameter_property PERIOD_SYNC_US ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PERIOD_SYNC_US HDL_PARAMETER true
add_parameter LINK_0_FREQUENCY_MHZ INTEGER 50
set_parameter_property LINK_0_FREQUENCY_MHZ DEFAULT_VALUE 50
set_parameter_property LINK_0_FREQUENCY_MHZ DISPLAY_NAME "LINK 0 FREQUENCY (MHZ)"
set_parameter_property LINK_0_FREQUENCY_MHZ TYPE INTEGER
set_parameter_property LINK_0_FREQUENCY_MHZ UNITS None
set_parameter_property LINK_0_FREQUENCY_MHZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LINK_0_FREQUENCY_MHZ HDL_PARAMETER true
add_parameter LINK_0_NUM_BYTES INTEGER 500
set_parameter_property LINK_0_NUM_BYTES DEFAULT_VALUE 500
set_parameter_property LINK_0_NUM_BYTES DISPLAY_NAME "LINK 0 NUM_BYTES"
set_parameter_property LINK_0_NUM_BYTES TYPE INTEGER
set_parameter_property LINK_0_NUM_BYTES UNITS None
set_parameter_property LINK_0_NUM_BYTES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LINK_0_NUM_BYTES HDL_PARAMETER true
add_parameter LINK_2_FREQUENCY_MHZ INTEGER 20
set_parameter_property LINK_2_FREQUENCY_MHZ DEFAULT_VALUE 20
set_parameter_property LINK_2_FREQUENCY_MHZ DISPLAY_NAME "LINK 2 FREQUENCY (MHZ)"
set_parameter_property LINK_2_FREQUENCY_MHZ TYPE INTEGER
set_parameter_property LINK_2_FREQUENCY_MHZ UNITS None
set_parameter_property LINK_2_FREQUENCY_MHZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LINK_2_FREQUENCY_MHZ HDL_PARAMETER true
add_parameter LINK_2_NUM_BYTES INTEGER 80
set_parameter_property LINK_2_NUM_BYTES DEFAULT_VALUE 80
set_parameter_property LINK_2_NUM_BYTES DISPLAY_NAME "LINK 2 NUM_BYTES"
set_parameter_property LINK_2_NUM_BYTES TYPE INTEGER
set_parameter_property LINK_2_NUM_BYTES UNITS None
set_parameter_property LINK_2_NUM_BYTES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LINK_2_NUM_BYTES HDL_PARAMETER true

add_display_item "General Parameters" PERIOD_SYNC_US PARAMETER ""
add_display_item "Link 0 and 1" LINK_0_FREQUENCY_MHZ PARAMETER ""
add_display_item "Link 0 and 1" LINK_0_NUM_BYTES PARAMETER ""
add_display_item "Link 2" LINK_2_FREQUENCY_MHZ PARAMETER ""
add_display_item "Link 2" LINK_2_NUM_BYTES PARAMETER ""


# 
# display items
# 


# 
# connection point sysclk
# 
add_interface sysclk clock end
set_interface_property sysclk clockRate 0
set_interface_property sysclk ENABLED true
set_interface_property sysclk EXPORT_OF ""
set_interface_property sysclk PORT_NAME_MAP ""
set_interface_property sysclk CMSIS_SVD_VARIABLES ""
set_interface_property sysclk SVD_ADDRESS_GROUP ""

add_interface_port sysclk sysclk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock ""
set_interface_property reset_n synchronousEdges NONE
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rst_n reset_n Input 1



# 
# connection point avmm
# 
add_interface avmm avalon end
set_interface_property avmm addressUnits WORDS
set_interface_property avmm associatedClock sysclk
set_interface_property avmm associatedReset reset_n
set_interface_property avmm bitsPerSymbol 8
set_interface_property avmm burstOnBurstBoundariesOnly false
set_interface_property avmm burstcountUnits WORDS
set_interface_property avmm explicitAddressSpan 0
set_interface_property avmm holdTime 0
set_interface_property avmm linewrapBursts false
set_interface_property avmm maximumPendingReadTransactions 0
set_interface_property avmm maximumPendingWriteTransactions 0
set_interface_property avmm readLatency 0
set_interface_property avmm readWaitTime 1
set_interface_property avmm setupTime 0
set_interface_property avmm timingUnits Cycles
set_interface_property avmm writeWaitTime 0
set_interface_property avmm ENABLED true
set_interface_property avmm EXPORT_OF ""
set_interface_property avmm PORT_NAME_MAP ""
set_interface_property avmm CMSIS_SVD_VARIABLES ""
set_interface_property avmm SVD_ADDRESS_GROUP ""

add_interface_port avmm avmm_address address Input 4
add_interface_port avmm avmm_write write Input 1
add_interface_port avmm avmm_read read Input 1
add_interface_port avmm avmm_readdata readdata Output 32
add_interface_port avmm avmm_writedata writedata Input 32
set_interface_assignment avmm embeddedsw.configuration.isFlash 0
set_interface_assignment avmm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point c0_clk
# 
add_interface c0_clk clock end
set_interface_property c0_clk clockRate 0
set_interface_property c0_clk ENABLED true
set_interface_property c0_clk EXPORT_OF ""
set_interface_property c0_clk PORT_NAME_MAP ""
set_interface_property c0_clk CMSIS_SVD_VARIABLES ""
set_interface_property c0_clk SVD_ADDRESS_GROUP ""

add_interface_port c0_clk clk0_0 clk Input 1


# 
# connection point c0_clk90
# 
add_interface c0_clk90 clock end
set_interface_property c0_clk90 clockRate 0
set_interface_property c0_clk90 ENABLED true
set_interface_property c0_clk90 EXPORT_OF ""
set_interface_property c0_clk90 PORT_NAME_MAP ""
set_interface_property c0_clk90 CMSIS_SVD_VARIABLES ""
set_interface_property c0_clk90 SVD_ADDRESS_GROUP ""

add_interface_port c0_clk90 clk0_90 clk Input 1


# 
# connection point c2_clk
# 
add_interface c2_clk clock end
set_interface_property c2_clk clockRate 0
set_interface_property c2_clk ENABLED true
set_interface_property c2_clk EXPORT_OF ""
set_interface_property c2_clk PORT_NAME_MAP ""
set_interface_property c2_clk CMSIS_SVD_VARIABLES ""
set_interface_property c2_clk SVD_ADDRESS_GROUP ""

add_interface_port c2_clk clk2_0 clk Input 1


# 
# connection point c2_clk90
# 
add_interface c2_clk90 clock end
set_interface_property c2_clk90 clockRate 0
set_interface_property c2_clk90 ENABLED true
set_interface_property c2_clk90 EXPORT_OF ""
set_interface_property c2_clk90 PORT_NAME_MAP ""
set_interface_property c2_clk90 CMSIS_SVD_VARIABLES ""
set_interface_property c2_clk90 SVD_ADDRESS_GROUP ""

add_interface_port c2_clk90 clk2_90 clk Input 1


# 
# connection point rj45A_connector
# 
add_interface rj45A_connector conduit end
set_interface_property rj45A_connector associatedClock sysclk
set_interface_property rj45A_connector associatedReset ""
set_interface_property rj45A_connector ENABLED true
set_interface_property rj45A_connector EXPORT_OF ""
set_interface_property rj45A_connector PORT_NAME_MAP ""
set_interface_property rj45A_connector CMSIS_SVD_VARIABLES ""
set_interface_property rj45A_connector SVD_ADDRESS_GROUP ""

add_interface_port rj45A_connector tx0_serial_o tx0 Output 1
add_interface_port rj45A_connector rx1_serial_i rx1 Input 1
add_interface_port rj45A_connector tx2_serial_o tx2 Output 1

# 
# connection point rj45B_connector
# 
add_interface rj45B_connector conduit end
set_interface_property rj45B_connector associatedClock sysclk
set_interface_property rj45B_connector associatedReset ""
set_interface_property rj45B_connector ENABLED true
set_interface_property rj45B_connector EXPORT_OF ""
set_interface_property rj45B_connector PORT_NAME_MAP ""
set_interface_property rj45B_connector CMSIS_SVD_VARIABLES ""
set_interface_property rj45B_connector SVD_ADDRESS_GROUP ""

add_interface_port rj45B_connector rx0_serial_i rx0 Input 1
add_interface_port rj45B_connector tx1_serial_o tx1 Output 1
add_interface_port rj45B_connector rx2_serial_i rx2 Input 1

